// Code generated by "stringer -type=SegmentationSupport"; DO NOT EDIT.

package bacnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SegmentationSupportBoth-0]
	_ = x[SegmentationSupportTransmit-1]
	_ = x[SegmentationSupportReceive-2]
	_ = x[SegmentationSupportNone-3]
}

const _SegmentationSupport_name = "SegmentationSupportBothSegmentationSupportTransmitSegmentationSupportReceiveSegmentationSupportNone"

var _SegmentationSupport_index = [...]uint8{0, 23, 50, 76, 99}

func (i SegmentationSupport) String() string {
	if i >= SegmentationSupport(len(_SegmentationSupport_index)-1) {
		return "SegmentationSupport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SegmentationSupport_name[_SegmentationSupport_index[i]:_SegmentationSupport_index[i+1]]
}
