// Code generated by "stringer -type=NPDUPriority"; DO NOT EDIT.

package bacip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LifeSafety-3]
	_ = x[CriticalEquipment-2]
	_ = x[Urgent-1]
	_ = x[Normal-0]
}

const _NPDUPriority_name = "NormalUrgentCriticalEquipmentLifeSafety"

var _NPDUPriority_index = [...]uint8{0, 6, 12, 29, 39}

func (i NPDUPriority) String() string {
	if i >= NPDUPriority(len(_NPDUPriority_index)-1) {
		return "NPDUPriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NPDUPriority_name[_NPDUPriority_index[i]:_NPDUPriority_index[i+1]]
}
